// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0R0C5G-8ENKOmqScs7bhkN7EZgKDX-us',
    appId: '1:921446424868:web:def7a2d9088fff1dd6d3b1',
    messagingSenderId: '921446424868',
    projectId: 'sos-electricity-app',
    authDomain: 'sos-electricity-app.firebaseapp.com',
    storageBucket: 'sos-electricity-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMSb74CXyrG_-eIg9INuZPIlm6t79G1EM',
    appId: '1:921446424868:android:c4069a4d62c951a5d6d3b1',
    messagingSenderId: '921446424868',
    projectId: 'sos-electricity-app',
    storageBucket: 'sos-electricity-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoTB27gYwmFJPetYcRbqIeQUOz8yaimVE',
    appId: '1:921446424868:ios:cb8a22cba1963c9fd6d3b1',
    messagingSenderId: '921446424868',
    projectId: 'sos-electricity-app',
    storageBucket: 'sos-electricity-app.firebasestorage.app',
    iosBundleId: 'com.example.electricityAppAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoTB27gYwmFJPetYcRbqIeQUOz8yaimVE',
    appId: '1:921446424868:ios:cb8a22cba1963c9fd6d3b1',
    messagingSenderId: '921446424868',
    projectId: 'sos-electricity-app',
    storageBucket: 'sos-electricity-app.firebasestorage.app',
    iosBundleId: 'com.example.electricityAppAdmin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0R0C5G-8ENKOmqScs7bhkN7EZgKDX-us',
    appId: '1:921446424868:web:f01f7b4aa95f5de0d6d3b1',
    messagingSenderId: '921446424868',
    projectId: 'sos-electricity-app',
    authDomain: 'sos-electricity-app.firebaseapp.com',
    storageBucket: 'sos-electricity-app.firebasestorage.app',
  );
}
